imports:
    - { resource: "../vendor/sylius/sylius/src/Sylius/Behat/Resources/config/services.xml" }
    - { resource: "../tests/Behat/Resources/config/services.yml" }
    
sylius_api:
    enabled: true
